---
- hosts: gcloud

  tasks:
     - ping: ~
     - name: Update APT pakage manager repositories cache

       become: true

       apt:

         update_cache: yes

     - name: Upgrade installed pakages

       become: true

       apt:

         upgrade: dist


     - name: Install cowsay - it's probabily important

       apt:

         name: cowsay
       become: true


     - name: Install Git VSC

       become: true

       apt:

         name: git

         state: latest
     - name: Install nginx webserver

       become: true

       apt:

        name: nginx

        state: latest

     - name: add PHP 7 ppa repository

       become: true

       apt_repository:

            repo: 'ppa:ondrej/php'

     - name: Install PHP packages

       become: true

       apt:

         name: "{{ item }}"

         state: latest

       with_items:
         - php7.1-cli
         - php7.1-curl
         - php7.1-fpm
         - php7.1-mysql
         - php7.1-intl